#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SampleXamarin.Resource", IsApplication=true)]

namespace SampleXamarin
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorHint = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimary = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int colorPrimaryDark = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int launcher_foreground = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int sensorStatusAvailable = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int sensorStatusBlocked = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int sensorStatusIndeterminate = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int sensorStatusUnavailable = 2130771976;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int actionButton = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int add_anchor = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int anchorNumText = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int arBasicDemo = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int arNearbyDemo = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int arSharedDemo = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int ar_fragment = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int backButton = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int back_button = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int bluetooth_status = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int coarseRelocDemoButton = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int coarseRelocDemoLabel = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int confirm_placement = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int createButton = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int create_anchor = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int cube_shape = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int cylinder_shape = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int editTextInfo = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int geolocation_status = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int hint_text = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int linearLayout = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int locateButton = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int mainMenu = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int recommended_scan_progress = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int required_scan_progress = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int scanProgressText = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int sensor_status = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int shape_selection = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int sphere_shape = 2130837532;
			
			// aapt resource value: 0x7F02001D
			public const int start_watcher = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int statusText = 2130837534;
			
			// aapt resource value: 0x7F02001F
			public const int stop_watcher = 2130837535;
			
			// aapt resource value: 0x7F020020
			public const int textView = 2130837536;
			
			// aapt resource value: 0x7F020021
			public const int textView3 = 2130837537;
			
			// aapt resource value: 0x7F020022
			public const int textView4 = 2130837538;
			
			// aapt resource value: 0x7F020023
			public const int textView5 = 2130837539;
			
			// aapt resource value: 0x7F020024
			public const int titleText = 2130837540;
			
			// aapt resource value: 0x7F020025
			public const int ux_frame = 2130837541;
			
			// aapt resource value: 0x7F020026
			public const int wifi_status = 2130837542;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int activity_anchors = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int activity_coarse_reloc = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int activity_main = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int activity_shared = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int coarse_reloc_action_selection = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int coarse_reloc_anchor_creation = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int coarse_reloc_anchor_placement = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int coarse_reloc_watcher = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int sensor_status = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F040000
			public const int ic_launcher = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int ic_launcher_foreground = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int ic_launcher_round = 2130968578;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F050000
			public const int add_anchor = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int back = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int back_button_text = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int bluetooth_status = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int confirm_placement = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int create_anchor = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int create_button_text = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int geolocation_status = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int hint_adjust_anchor = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int hint_place_anchor = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int hint_scan_for_anchors = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int hint_scan_for_creation = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int large_circle = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int locate_button_text = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public const int main_basic_button_text = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int main_basic_details_text = 2131034128;
			
			// aapt resource value: 0x7F050011
			public const int main_coarse_reloc_button_text = 2131034129;
			
			// aapt resource value: 0x7F050012
			public const int main_coarse_reloc_details_text = 2131034130;
			
			// aapt resource value: 0x7F050013
			public const int main_nearby_button_text = 2131034131;
			
			// aapt resource value: 0x7F050014
			public const int main_nearby_details_text = 2131034132;
			
			// aapt resource value: 0x7F050015
			public const int main_shared_button_text = 2131034133;
			
			// aapt resource value: 0x7F050016
			public const int main_shared_details_text = 2131034134;
			
			// aapt resource value: 0x7F050017
			public const int main_title_text = 2131034135;
			
			// aapt resource value: 0x7F050018
			public const int recommended_scan_progress = 2131034136;
			
			// aapt resource value: 0x7F050019
			public const int required_scan_progress = 2131034137;
			
			// aapt resource value: 0x7F05001A
			public const int shared_anchor_number_text = 2131034138;
			
			// aapt resource value: 0x7F05001B
			public const int shared_enter_anchor_text = 2131034139;
			
			// aapt resource value: 0x7F05001C
			public const int shared_title_text = 2131034140;
			
			// aapt resource value: 0x7F05001D
			public const int start_watcher = 2131034141;
			
			// aapt resource value: 0x7F05001E
			public const int stop_watcher = 2131034142;
			
			// aapt resource value: 0x7F05001F
			public const int title_activity_aractive = 2131034143;
			
			// aapt resource value: 0x7F050020
			public const int wifi_status = 2131034144;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F060000
			public const int AppTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
